server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Gère le routage de l'Application Single Page (React)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Options de cache pour les fichiers statiques
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000";
    }
}
