using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SchoolERP.Domain.Academic;
using SchoolERP.Domain.Enums;
using SchoolERP.Domain.HR;
using SchoolERP.Domain.Interfaces;
using SchoolERP.Domain.Payroll;
using SchoolERP.Domain.Finance;
using SchoolERP.Domain.Events;
using SchoolERP.Domain.Auth;
using SchoolERP.Application.Common.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace SchoolERP.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
[Authorize(Roles = "SuperAdmin")]
public class SeedController : ControllerBase
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly ITenantService _tenantService;
    private readonly IPasswordHasher _passwordHasher;

    public SeedController(IUnitOfWork unitOfWork, ITenantService tenantService, IPasswordHasher passwordHasher)
    {
        _unitOfWork = unitOfWork;
        _tenantService = tenantService;
        _passwordHasher = passwordHasher;
    }

    [HttpPost("demo-data")]
    [AllowAnonymous]
    public async Task<IActionResult> SeedDemoData()
    {
        var db = (DbContext)_unitOfWork;
        // 1. Check if already seeded
        // if (await db.Set<School>().AnyAsync()) return BadRequest("Database already has data.");

        // 1.5 Create Default School
        var school = School.Create("LycÃ©e Bamako", "LYC-BKO", "Baco Djicoroni", "Bamako", "Mali", "+223 70 00 00 00", "contact@lyceebamako.ml", SchoolType.Private);
        db.Add(school);

        // 1.6 Create System School for Global Data (like SuperAdmin) if it doesn't exist
        var systemSchoolId = Guid.Empty;
        if (!await db.Set<School>().AnyAsync(s => s.Id == systemSchoolId))
        {
            var systemSchool = School.Create("System", "SYSTEM", "N/A", "N/A", "N/A", "N/A", "system@schoolerp.com", SchoolType.Private);
            // We use reflection to set Id to Guid.Empty as it's generated by default
            typeof(School).GetProperty("Id", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)?
                .SetValue(systemSchool, systemSchoolId);
            db.Add(systemSchool);
        }

        await _unitOfWork.SaveChangesAsync();
        
        var tenantId = school.Id;

        // 2. Academic Year
        var year = AcademicYear.Create(tenantId, "2023-2024", DateTime.UtcNow.AddMonths(-6), DateTime.UtcNow.AddMonths(6));
        db.Add(year);

        // 3. Classroom
        var cls = Classroom.Create(tenantId, "6Ã¨me A", "6A", 40, year.Id);
        db.Add(cls);

        // 4. Subject
        var math = Subject.Create(tenantId, "MathÃ©matiques", "MATH", 4.0m);
        var fr = Subject.Create(tenantId, "FranÃ§ais", "FR", 3.0m);
        db.Add(math); db.Add(fr);

        await _unitOfWork.SaveChangesAsync();

        // 5. Students & Enrollments
        for (int i = 1; i <= 20; i++)
        {
            var student = Student.Create(tenantId, $"Eleve{i}", "Nom", DateTime.UtcNow.AddYears(-12), Gender.Male, $"MAT{i:D4}", "Parent", "555-0123", "p@e.com", "Father");
            db.Add(student);
            
            var enrollment = Enrollment.Create(tenantId, student.Id, cls.Id, year.Id);
            db.Add(enrollment);

            // Add grades
            db.Add(Grade.Create(tenantId, student.Id, math.Id, year.Id, (decimal)(10 + i % 10), 20, 1, ExamType.Continuous, "Bien"));
            db.Add(Grade.Create(tenantId, student.Id, fr.Id, year.Id, (decimal)(12 + i % 8), 20, 1, ExamType.Continuous, "Assez bien"));
            
            // Add an invoice
            var inv = StudentInvoice.Create(tenantId, student.Id, year.Id, "Frais de ScolaritÃ© T1", 150000, FeeType.Tuition, DateTime.UtcNow.AddDays(30));
            db.Add(inv);
        }

        // 6. Employees & Payroll
        var dept = Department.Create(tenantId, "Administration", "ADM");
        db.Add(dept);
        await _unitOfWork.SaveChangesAsync();

        var emp = Employee.Create(tenantId, "Jean", "Dupont", "jean.d@school.com", "+225 11223344", DateTime.UtcNow.AddYears(-30), Gender.Male, DateTime.UtcNow.AddYears(-1), EmployeeType.Administrative, dept.Id);
        db.Add(emp);
        
        var contract = Contract.Create(tenantId, emp.Id, ContractType.CDI, DateTime.UtcNow.AddYears(-1), null, 450000);
        db.Add(contract); 

        await _unitOfWork.SaveChangesAsync();

        // 7. School Calendar Events
        await SeedSchoolEvents(db, tenantId);

        // 8. Real Users
        await SeedUsers(db, tenantId);

        return Ok("Demo data seeded successfully with 20 students, classes, subjects, invoices, 1 employee, school calendar events AND real DB-backed users.");
    }

    private async Task SeedUsers(DbContext db, Guid tenantId)
    {
        var hasher = _passwordHasher;
        
        // LycÃ©e Bamako Admin (Tenant Specific)
        if (!await db.Set<User>().AnyAsync(u => u.Email == "admin@school.com"))
        {
            db.Add(Domain.Auth.User.Create(tenantId, "admin@school.com", hasher.HashPassword("Admin@1234"), "Admin", "Principal", UserRole.SchoolAdmin));
            db.Add(Domain.Auth.User.Create(tenantId, "rh@school.com", hasher.HashPassword("Admin@1234"), "Fatou", "KonÃ©", UserRole.HR_Manager));
            db.Add(Domain.Auth.User.Create(tenantId, "prof@school.com", hasher.HashPassword("Admin@1234"), "Ibrahim", "Diallo", UserRole.Teacher));
            db.Add(Domain.Auth.User.Create(tenantId, "comptable@school.com", hasher.HashPassword("Admin@1234"), "Marie", "Traore", UserRole.Accountant));
            db.Add(Domain.Auth.User.Create(tenantId, "eleve@school.com", hasher.HashPassword("Admin@1234"), "Eleve", "Demo", UserRole.Student));
        }

        // Platform SuperAdmin (Global)
        var superAdminId = Guid.Empty;
        if (!await db.Set<User>().AnyAsync(u => u.Email == "super@schoolerp.com"))
        {
            db.Add(Domain.Auth.User.Create(superAdminId, "super@schoolerp.com", hasher.HashPassword("Super@1234"), "Super", "Admin", UserRole.SuperAdmin));
        }

        await _unitOfWork.SaveChangesAsync();
    }

    [HttpPost("school-events")]
    public async Task<IActionResult> SeedSchoolEventsOnly()
    {
        var db = (DbContext)_unitOfWork;
        var tenantId = _tenantService.GetCurrentTenantId();

        // Remove existing seeded events if re-running
        var existing = await db.Set<SchoolEvent>().ToListAsync();
        db.Set<SchoolEvent>().RemoveRange(existing);
        await _unitOfWork.SaveChangesAsync();

        await SeedSchoolEvents(db, tenantId);
        return Ok("Calendrier scolaire 2024-2025 gÃ©nÃ©rÃ© avec succÃ¨s !");
    }

    private async Task SeedSchoolEvents(DbContext db, Guid tenantId)
    {
        var events = new List<SchoolEvent>
        {
            // â”€â”€ RentrÃ©e & Orientation â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
            SchoolEvent.Create(tenantId, "RentrÃ©e scolaire 2024-2025", "Accueil des Ã©lÃ¨ves et remise des emplois du temps", new DateTime(2024, 9, 2), new DateTime(2024, 9, 2), EventCategory.Ceremony, true, "Cour de rÃ©crÃ©ation"),
            SchoolEvent.Create(tenantId, "RÃ©union de rentrÃ©e parents-professeurs", "PrÃ©sentation des enseignants et du rÃ¨glement intÃ©rieur", new DateTime(2024, 9, 6), new DateTime(2024, 9, 6), EventCategory.Meeting, true, "Salle de confÃ©rence"),

            // â”€â”€ 1er Trimestre Oct-Nov â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
            SchoolEvent.Create(tenantId, "ContrÃ´le du 1er Trimestre - Math & Sciences", "ContrÃ´le continu toutes classes", new DateTime(2024, 10, 7), new DateTime(2024, 10, 11), EventCategory.Exam, false, "Salles de classe"),
            SchoolEvent.Create(tenantId, "ContrÃ´le du 1er Trimestre - Lettres & Langues", "ContrÃ´le continu toutes classes", new DateTime(2024, 10, 14), new DateTime(2024, 10, 18), EventCategory.Exam, false, "Salles de classe"),
            SchoolEvent.Create(tenantId, "JournÃ©e sportive du 1er trimestre ðŸ†", "ComplÃ¨te Football, AthlÃ©tisme, Basketball inter-classes", new DateTime(2024, 11, 8), new DateTime(2024, 11, 8), EventCategory.Sports, true, "Terrain de sport"),
            SchoolEvent.Create(tenantId, "Consei de classe 1er Trimestre", "DÃ©libÃ©ration et remise des bulletins", new DateTime(2024, 11, 22), new DateTime(2024, 11, 22), EventCategory.Meeting, true, "Salle des professeurs"),

            // â”€â”€ Vacances de NoÃ«l â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
            SchoolEvent.Create(tenantId, "ðŸŽ„ Vacances de NoÃ«l", "Vacances scolaires de fin d'annÃ©e", new DateTime(2024, 12, 23), new DateTime(2025, 1, 3), EventCategory.Holiday, true),

            // â”€â”€ 2Ã¨me Trimestre Jan-Mar â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
            SchoolEvent.Create(tenantId, "Reprise des cours - 2Ã¨me Trimestre", null, new DateTime(2025, 1, 6), new DateTime(2025, 1, 6), EventCategory.Ceremony, true),
            SchoolEvent.Create(tenantId, "Examens blancs 2Ã¨me Trimestre", "Simulation des examens officiels sur l'ensemble du programme", new DateTime(2025, 2, 3), new DateTime(2025, 2, 7), EventCategory.Exam, false, "Salles de classe"),
            SchoolEvent.Create(tenantId, "Sortie Ã©ducative - MusÃ©e National ðŸ›ï¸", "Visite culturelle pour toutes les classes de 4Ã¨me et 3Ã¨me", new DateTime(2025, 2, 14), new DateTime(2025, 2, 14), EventCategory.SchoolTrip, true, "MusÃ©e National"),
            SchoolEvent.Create(tenantId, "FÃªte de l'IndÃ©pendance ðŸŽ‰", "Jour FÃ©riÃ© - Ã‰tablissement fermÃ©", new DateTime(2025, 2, 28), new DateTime(2025, 2, 28), EventCategory.Holiday, true),
            SchoolEvent.Create(tenantId, "ContrÃ´le de mi-trimestre - Toutes matiÃ¨res", null, new DateTime(2025, 3, 3), new DateTime(2025, 3, 7), EventCategory.Exam, false),
            SchoolEvent.Create(tenantId, "Conseil de classe 2Ã¨me Trimestre", "DÃ©libÃ©rations et orientation des Ã©lÃ¨ves", new DateTime(2025, 3, 21), new DateTime(2025, 3, 21), EventCategory.Meeting, true, "Salle des professeurs"),

            // â”€â”€ Vacances de PÃ¢ques â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
            SchoolEvent.Create(tenantId, "ðŸ£ Vacances de PÃ¢ques", "Vacances de printemps", new DateTime(2025, 4, 7), new DateTime(2025, 4, 18), EventCategory.Holiday, true),

            // â”€â”€ 3Ã¨me Trimestre Avr-Juin â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
            SchoolEvent.Create(tenantId, "Reprise des cours - 3Ã¨me Trimestre", null, new DateTime(2025, 4, 22), new DateTime(2025, 4, 22), EventCategory.Ceremony, true),
            SchoolEvent.Create(tenantId, "JournÃ©e portes ouvertes ðŸ«", "Accueil des futurs Ã©lÃ¨ves et de leurs parents", new DateTime(2025, 5, 3), new DateTime(2025, 5, 3), EventCategory.Ceremony, true, "Tout l'Ã©tablissement"),
            SchoolEvent.Create(tenantId, "Examens de fin d'annÃ©e - 1Ã¨re session", "Examens officiels de fin d'annÃ©e scolaire", new DateTime(2025, 5, 26), new DateTime(2025, 6, 6), EventCategory.Exam, false, "Salles d'examen"),
            SchoolEvent.Create(tenantId, "Tournoi de football inter-Ã©tablissements", "CompÃ©tition sportive rÃ©gionale", new DateTime(2025, 6, 7), new DateTime(2025, 6, 7), EventCategory.Sports, true, "Stade municipal"),
            SchoolEvent.Create(tenantId, "DÃ©libÃ©ration et jury de fin d'annÃ©e", null, new DateTime(2025, 6, 13), new DateTime(2025, 6, 13), EventCategory.Meeting, true, "Salle de confÃ©rence"),
            SchoolEvent.Create(tenantId, "ðŸŽ“ CÃ©rÃ©monie de remise des diplomes", "Remise des diplomes et distinction des Ã©lÃ¨ves mÃ©ritants", new DateTime(2025, 6, 20), new DateTime(2025, 6, 20), EventCategory.Ceremony, true, "Salle des fÃªtes"),
            SchoolEvent.Create(tenantId, "â˜€ï¸ Grandes vacances 2025", "Fin de l'annÃ©e scolaire 2024-2025", new DateTime(2025, 6, 28), new DateTime(2025, 9, 1), EventCategory.Holiday, true),
        };

        await db.Set<SchoolEvent>().AddRangeAsync(events);
        await _unitOfWork.SaveChangesAsync();
    }
}
